### ISSUE TITLE
Server must be present, spec says it's optional.

### ISSUE THREAD

**Issue by Booktivity** [Redocly/redocly-vs-code#11]
**What happened?**

Validation error is shown (red lines) if servers field is missing in spec.

**What should have happened instead?**

servers field is not required based on [openapi 3.03]( https://swagger.io/specification/).

**Minimal reproducible OpenAPI snippet**

```
openapi: 3.0.3
info: {title: '', version: ''}
components: {}
paths:
  /path:
    summary: TODO
```

**Screenshots**
<img width="476" alt="Screenshot 2022-02-07 at 11 40 19" src="https://user-images.githubusercontent.com/19308169/152772827-a40f0c65-b932-4a6d-b621-4a3ddf8cae85.png">

**Additional context**

Redocly OpenAPI v0.2.3

.redocly.yaml contents:

```
apiDefinitions:
  root: hidden.yaml
lint:
  extends:
    - recommended
  rules:
    tag-description: off
    operation-summary: error
    no-unresolved-refs: error
    no-unused-components: error
    operation-2xx-response: error
    operation-operationId: error
    operation-singular-tag: error
    no-enum-type-mismatch: error
    no-identical-paths: error
    no-ambiguous-paths: error
```
