### ISSUE TITLE
Improve the default `redocly.yaml` file

### ISSUE THREAD

**Issue by adamaltman** [Redocly/redocly-vs-code#25]
**What should we improve?**

We offer a default Redocly configuration file when we detect an openapi definition.

**How should we improve it?**

1. Rename it from `.redocly.yaml` to `redocly.yaml`.
2. Replace the contents of the file with the one below, but be sure to change the path to the root file detected.

```yaml
# See https://redocly.com/docs/cli/configuration/configuration-file/ for information on how to customize your configuration

apis:
  changeme@v1:
    root: ./openapi.yaml

lint:
  extends:
    - recommended
  rules:
    paths-kebab-case: error

features.openapi:
  generateCodeSamples:
    languages:
      - lang: curl
      - lang: Node.js
      - lang: Python
```

**Why should we improve it?**

The current one doesn't actually work and requires the user to make a lot of changes.

**Describe alternatives you've considered**

- Removing the `apis` section.
- 
**Additional context**

The current generated file:

```yaml
apiDefinitions:
  # a set of named keys and values of entrypoints to OpenAPI definitions.
  # example
  # petstore: ./openapi.yaml

lint:
# the lint options

referenceDocs:
# the API reference docs options, including theme options.
```
