### ISSUE TITLE
Handle multi-root Workspaces

### ISSUE THREAD

**Issue by IgorKarpiuk** [Redocly/redocly-vs-code#37]
**What should we improve?**

Users can have several projects in vs code workspace . Each project can have its own configuration file. The goal is to find the correct configuration depending on the file selected by the user and highlight errors and warnings in OpenAPI definition files according to the configuration

**How should we improve it?**

The extension should select the root folder and look for the configuration file there depending on the file opened by the user

**Why should we improve it?**

Currently, the extension does not work correctly with Multi-root Workspaces

**Describe alternatives you've considered**

To do nothing

**Additional context**

[Multi-root Workspaces](https://code.visualstudio.com/docs/editor/multi-root-workspaces)

**Comment by unional** [comment]
Just sharing that I also have the same need.

**Comment by jeremyfiel** [comment]
Would be great to have this functionality!  @lornajane

**Comment by adamaltman** [comment]
Does the apis feature of the config file, where you can specify different paths to the root files serve as an alternative?

```
apis:
  example1: 
     root: ./path/to/file.yaml
     rules:
       # some rules
  example2: 
     root: ./path/to/file.yaml
     rules:
       # some rules
```
