### ISSUE TITLE
Parsing other yaml files leads to problem report without a source

### ISSUE THREAD

**Issue by eseglem** [Redocly/redocly-vs-code#51]
**What happened?**

The extension tries to read all yaml files in the workspace and not all of them are OpenAPI. Any yaml with custom tags seem to confuse the extension. Rather than reporting nicely, it ends up with a problem without a "source". 

```json
[{
	"resource": "/path/to/example.yaml",
	"owner": "_generated_diagnostic_collection_name_#0",
	"severity": 8,
	"message": "unknown tag !<!GetAtt> in \"/path/to/example.yaml\" (12:13)",
	"startLineNumber": 12,
	"startColumn": 13,
	"endLineNumber": 12,
	"endColumn": 13
}]
```

**What should have happened instead?**

- Handle reading non OpenAPI yaml with custom tags and report the issue with a "source" included so it is easier to track down. 
- It would be nice to allow explicit include / exclude of files / directories that the extension will check. Then it does not need to deal with files which aren't OpenAPI. 

**Minimal reproducible ~OpenAPI~ snippet**

CloudFormation from: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/gettingstarted.templatebasics.html

```yaml
Resources:
  myBucket:
    Type: 'AWS::S3::Bucket'
  myDistribution:
    Type: 'AWS::CloudFront::Distribution'
    Properties:
      DistributionConfig:
        Origins:
          - DomainName: !GetAtt 
              - myBucket
              - DomainName
            Id: myS3Origin
            S3OriginConfig: {}
        Enabled: 'true'
        DefaultCacheBehavior:
          TargetOriginId: myS3Origin
          ForwardedValues:
            QueryString: 'false'
          ViewerProtocolPolicy: allow-all
```

**Additional context**

This made it quite difficult to track down where the reported problem was coming from. It required disabling extensions until the problem disappeared to figure out it was Redocly.
