### ISSUE TITLE
`suggest` configurable rule attribute does not display full list

### ISSUE THREAD

**Issue by jeremyfiel** [Redocly/redocly-vs-code#78]
**What happened?**

when using `suggest` in a configurable rule, the full list of suggestions are not displayed to the user. 

**What should have happened instead?**

The full list of suggestions should be displayed

**Minimal reproducible OpenAPI snippet**

```yaml
openapi: 3.0.4
info:
  title: suggest test
  version: 0.0.1
paths:
  '/bar':
    get:
      servers:
      - url: https://bar.domain.com
      summary: get all things from bar
      responses:
        '200':
          description: OK
          content:
            'application/json':
              schema:
                type: object
                items: {}

```

```yaml
rules:
  rule/type-object-allowed-keywords:
    message: '"type: object" with {{property}} is not allowed'
    severity: error
    where:
      - subject:
          type: Schema
          property: type
        assertions:
          defined: true
          const: object
    subject:
      type: Schema
    assertions:
      requireAny:
        - properties
        - patternProperties
        - additionalProperties
        - allOf
        - oneOf
        - anyOf
      disallowed:
        - items
        - minItems
        - maxItems
    suggest:
      - properties
      - patternProperties
      - additionalProperties
      - allOf
      - oneOf
      - anyOf
```

**Screenshots**

This happens on both the hover tool tip
![Image](https://github.com/user-attachments/assets/6f934f62-29ba-4c69-a309-897c957a5f39)

and the Problems tab.
![Image](https://github.com/user-attachments/assets/4097b9fc-b8bd-4427-bfdc-4a78142cc2d7)

**Additional context**

Redocly VSCode: 0.5.19
